name: ad_a_coffee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  fl_chart: ^1.2.0
  intl: ^0.18.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/menu_01.png
    - assets/images/menu_02.png
    - assets/images/menu_03.png
    - assets/images/menu_04.png
    - assets/images/menu_05.png
    - assets/images/menu_06.png
    - assets/images/menu_07.png